server:
  port: 9000
  
spring:
  application:
    name: plan-estimation-service
    
#cable-interent-catalog:
  #ribbon:
    #listOfServers: http://localhost:8080,http://localhost:8081
    
eureka:
  client:
    service-url: 
      default-zone: http://localhost:8761/eureka
    